### ISSUE TITLE
Tanji appears as a trojan-malware 

### ISSUE THREAD

**Issue by Antoni0240** [ArachisH/Tanji#12]
my antivirus told me that's an malware three times, it is dangerous for my device??
may i have a explanation why it is and if is dangerous to my device? thx btw

**Comment by Kobi-Blade** [comment]
It's a false positive... Meaning it's not dangerous at all for your device.

**Comment by ArachisH** [comment]
There are a couple reasons why an AV would flag the application as malicious
* Installs a self-signed certificate in the machine's root store(for HTTPS sniffing). This allows the application to detect, intercept, and modify any page related to 'Habbo'.
* Opens up one TCP port so that the game client communicates with the application, it will also open up a secondary TCP listener for 'remote' modules(Module Debugging for devs)

I also suggest that you **never** open this program with elevated permissions(NO ADMIN). Tanji has not needed to be run under admin since the 1.2 days.
